### ISSUE TITLE
Common

### ISSUE THREAD

**Issue by daswetter73** [Riemelt/Toxin#7]
1. Не запускается проект, вот одна из 7 ошибок:
![image](https://user-images.githubusercontent.com/92922078/219067281-fa3818b1-ecc7-4c11-91ff-612038a2a543.png)

**Comment by Riemelt** [comment]
@daswetter73 Должно работать сейчас.

**Comment by daswetter73** [comment]
2. Имена файлов в общем случае должны быть в kebab-case (неправильно: logoUIKit)

**Comment by daswetter73** [comment]
3. Лучше названия переменных не привязывать к цвету, тк если изменится цвет, то придется менять и название переменной. Можно использовать слова типа primary, secondary и другие подобные (dark-shade можно использовать)
![image](https://user-images.githubusercontent.com/92922078/224670246-71766989-a826-41fd-aa28-a690825d459c.png)
4. Ссылки на чужие страницы не дооформлены (2.12-2.13)
https://github.com/fullstack-development/front-end-best-practices/tree/master/HTML#2.12
