### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by daswetter73** [Riemelt/Toxin#8]
1. Такой выпадающий список лучше делать position: absolute, иначе сдвигается весь контент внизу
![image](https://user-images.githubusercontent.com/92922078/219290372-b183f7a5-7035-42ac-a4c0-3b3b8a3515ef.png)
2. Текст под заголовком тоже лучше сделать кликабельным
![image](https://user-images.githubusercontent.com/92922078/219290679-fe09b92b-c7ed-4efe-a027-8bab389f4c64.png)
3. При наведении странные стили: текст становится тусклым
![image](https://user-images.githubusercontent.com/92922078/219291007-aa689fcc-3a10-4b3e-b2ac-d06769e3cf6f.png)
4. На больших экранах лучше сделать так:
края страницы сделать в цвет футера и/или хедера (белый)
продолжить хедер/футер (без контента) и за края макета
![photo_2023-02-16_10-14-22](https://user-images.githubusercontent.com/92922078/219294439-bf1685b3-0976-4236-bbae-6bd4d8f772e3.jpg)
5. Кнопки кажутся слишком большими 
![image](https://user-images.githubusercontent.com/92922078/219295328-bd0775b6-4e2b-408d-9a85-a6edccb02323.png)
6. В планшетных/мобильных версиях лучше выравнивать по вертикали
![photo_2023-02-16_10-23-49](https://user-images.githubusercontent.com/92922078/219296195-96bcce0d-2c71-4f91-86bc-e4f12ae60251.jpg)
7. На мобилках можно сократить расстояния (на картинке) + всегда нужно следить, чтобы ничего не слипалось и оставлять хотя бы небольшое расстояние
![photo_2023-02-16_10-30-41](https://user-images.githubusercontent.com/92922078/219297643-3661d71f-e180-45b8-a8cc-8d76f8be0419.jpg)

**Comment by Riemelt** [comment]
3. В прошлом ишью ревьюер предлагал обозначить интерактивные элементы, убирая непрозрачность при наведении. Нужно убрать эти стили или изменить? И если текущие стили не подходят, то какие лучше сделать? Это нужно для всех элементов на сайте или только для радио-баттонов?

![Безымянный](https://user-images.githubusercontent.com/100680918/219438441-ddaaa761-ce41-459b-a62a-59d5a18bffd7.png)

**Comment by daswetter73** [comment]
3. Лучше изменить стили, сделав их более яркими, тк сейчас при наведении сложно прочитать текст. Какие именно - на выбор (другой цвет, подчеркивание и тд). Это нужно сделать для элементов, на которые навешаны такие стили.

**Comment by Riemelt** [comment]
@daswetter73 Готово.

**Comment by daswetter73** [comment]
8. В room details немного слетел респонсив
![image](https://user-images.githubusercontent.com/92922078/221592687-91c9779e-e037-4385-b9ce-6bb7c2f88b30.png)

**Comment by daswetter73** [comment]
9. Слипаются ссылки в футере (1268)
![image](https://user-images.githubusercontent.com/92922078/224661058-3f256188-72a6-4585-955f-9984c083001a.png)
и в room details (386)
![image](https://user-images.githubusercontent.com/92922078/224662787-4ca86a12-0fc8-4b04-994a-54fa866e69bb.png)
Еще желательно не отделять цифру от слова 
![image](https://user-images.githubusercontent.com/92922078/224663487-41c48c6f-b15c-4cba-b257-c85316bfe90f.png)
10. Лучше форму бронирования ставить выше (при адаптиве). Так будет приятнее и легче для юзера
11. У пароля должен быть соответствующий type инпута.
![image](https://user-images.githubusercontent.com/92922078/224664925-8204ad0c-6959-4420-ada4-b916454bfaa0.png)
