### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by daswetter73** [Riemelt/Toxin#9]
1. Тк БЭМ требует, чтобы блок был независим, необходимо, чтобы картинки, принадлежащие блоку, находились в папке с этим блоком
2. Модификатор _with-bigger-title (и другие подобные) звучит несколько нечетко. На мой взгляд лучше _title-size_big или _title-size_l
3. У блока button использованы булевые модификаторы, хотя нужны ключ-значение.

**Comment by Riemelt** [comment]
@daswetter73 
1. Перенёс logo свг файлы в logo компонент, но разве нужно переносить фотографии номеров и пользователей? Они ведь в теории могут быть переиспользованы в других блоках и вроде бы напрямую не зависят от конкретных компонентов. Та же карточка номеров со слайдером на вход получает много разных картинок.
3. Вроде бы в button как раз все опции в виде ключ-значений, кроме флага "hovered", но я немного изменил названия стилей, добавив префикс "theme".

**Comment by daswetter73** [comment]
1. В теории, конечно, может быть и так, но так как перед нами уже готовый проект, то видно, что, например, фото пользователей используются только для комментариев. Насчет фото номеров можно рассуждать по-разному, можно сделать по своему усмотрению
2. Имела в виду filled, bordered и тд. Если они ключ-значение, то ок

**Comment by Riemelt** [comment]
@daswetter73 

Распределил все картинки в компоненты, где они используются. Оставил только лэндинги, т.к. они на разных страницах есть.
